### ISSUE TITLE
Constant error from 'content.js'

### ISSUE THREAD

**Issue by sanjarcode** [crittermike/shortkeys#581]
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at Object.activateKey (content.js:1:16052)
    at content.js:1:16453
    at Array.forEach (<anonymous>)
    at content.js:1:16439
/client_204?atyp=i&biw=1280&bih=622&dpr=1&ei=j2YQZf2aG_CM2roP3vybsAw&opi=89978449:1     
```

Please fix

**Comment by yangfeng20** [comment]
Remember to pay attention to this bug, it kind of affects the experience, the console keeps reporting errors

**Comment by yangfeng20** [comment]
reference fix: https://github.com/crittermike/shortkeys/issues/338
